#!/usr/local/bin/ruby
require 'rubygems'
require 'fileutils'
include FileUtils

basedir = "/usr/local"
mkdir_p basedir

puts "Getting latest AWStats version"
aw_file=`lynx -dump http://sourceforge.net/projects/awstats/files/AWStats/ | egrep -i "awstats-[0-9\.]+\.(zip|tar.gz)\/download" | awk '{print $2}' | head -1`.strip

rc_dir = "/var/www/webmail/" + aw_file.match(/(awstats-[\d\.]+)\.(tar|zip)/)[1]

# make sure we're downloading the tar.gz file
aw_file.gsub!(/\.zip/, ".tar.gz")

puts "Downloading AWStats version " + aw_file.match(/([\d\.]+)\.(tar|zip)/)[1].to_s
system "ftp -Vmo - #{aw_file} | tar -zxf - -C #{basedir} -s /awstats-[0-9\.]*/awstats/"
puts "done"

