#!/usr/local/bin/ruby
require 'rubygems'
require 'fileutils'
include FileUtils

basedir = "/usr/local"
mkdir_p basedir

puts "Getting latest AWStats version"
aw_file=`lynx -dump http://sourceforge.net/projects/awstats/files/ | egrep "awstats-[0-9\.]+\.tar.gz\/download" | awk '{print $2}' | head -1`.strip

rc_dir = "/var/www/webmail/" + aw_file.match(/(awstats-[\d\.]+)\.tar/)[1]

puts "Downloading AWStats version " + aw_file.match(/([\d\.]+)\.tar/)[1].to_s
system "ftp -Vmo - #{aw_file} | tar -zxf - -C #{basedir} -s /awstats-[0-9\.]*/awstats/"
puts "done"
