#!/usr/local/bin/ruby
require 'rubygems'
require 'fileutils'
include FileUtils

basedir = "/usr/local"
mkdir_p basedir

puts "Getting latest AWStats version"
aw_file=`lynx -dump -listonly http://sourceforge.net/projects/awstats/files/AWStats/ | egrep "([0-9\.]\/)" | head -1 | awk '{print $2}' | xargs lynx -dump | egrep "(awstats-[0-9\.]+\.tar\.gz\/download)" | head -1 | awk '{ print $2 }'
`.strip

rc_dir = "/var/www/webmail/" + aw_file.match(/(awstats-[\d\.]+)\.(tar|zip)/)[1]

# make sure we're downloading the tar.gz file
aw_file.gsub!(/\.zip/, ".tar.gz")

puts "Downloading AWStats version " + aw_file.match(/([\d\.]+)\.(tar|zip)/)[1].to_s
system "ftp -Vmo - #{aw_file} | tar -zxf - -C #{basedir} -s /awstats-[0-9\.]*/awstats/"
puts "done"

